# Generated by Django 5.0.1 on 2024-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("necessary_tickets", models.CharField(max_length=100)),
                ("details", models.TextField(default="")),
                ("priority", models.CharField(default="", max_length=3)),
                ("state", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="NecessaryTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_master_ticket", models.IntegerField()),
                ("id_slave_ticket", models.IntegerField()),
            ],
            options={
                "unique_together": {("id_master_ticket", "id_slave_ticket")},
            },
        ),
    ]
