# Generated by Django 5.0.1 on 2024-01-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
