# Generated by Django 5.0.1 on 2024-01-23 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0002_alter_ticket_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="necessary_tickets",
        ),
    ]
