# Generated by Django 5.0.1 on 2024-01-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0003_remove_ticket_necessary_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="necessary_tickets",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="restApi.necessarytickets",
            ),
            preserve_default=False,
        ),
    ]
