# Generated by Django 5.0.1 on 2024-01-23 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0004_ticket_necessary_tickets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="necessary_tickets",
        ),
        migrations.DeleteModel(
            name="NecessaryTickets",
        ),
    ]
