# Generated by Django 5.0.1 on 2024-01-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0005_remove_ticket_necessary_tickets_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NecessaryTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_master_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_master_ticket",
                        to="restApi.ticket",
                    ),
                ),
                (
                    "id_slave_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_slave_ticket",
                        to="restApi.ticket",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_master_ticket", "id_slave_ticket")},
            },
        ),
    ]
