# Generated by Django 5.0.1 on 2024-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0007_ticket_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="test",
            field=models.ManyToManyField(default=None, to="restApi.ticket"),
        ),
    ]
