# Generated by Django 5.0.1 on 2024-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0008_alter_ticket_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="test",
        ),
        migrations.AddField(
            model_name="ticket",
            name="necessaryTickets",
            field=models.ManyToManyField(blank=True, default=None, to="restApi.ticket"),
        ),
    ]
