# Generated by Django 5.0.1 on 2024-01-23 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restApi", "0009_remove_ticket_test_ticket_necessarytickets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="necessaryTickets",
            new_name="necessary_tickets",
        ),
    ]
